name: C++ CI test run

on:
  push:
    branches: [ $default-branch develop ]
  pull_request:
    branches: [ $default-branch develop ]
  workflow_dispatch:

jobs:
  Makefile-test-run-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++-13, clang++-17]
        cxxstd: [c++11,c++14,c++17,c++20]
    steps:
      - uses: actions/checkout@v4
      - name: Check if example compiles
        run: make example
      - name: Run tests
        run: make test CXX=${{ matrix.compiler }} STD=${{ matrix.cxxstd }}
